from pymongo import MongoClient
import os
from dotenv import load_dotenv

load_dotenv('/app/backend/.env')

MONGO_URL = os.getenv("MONGO_URL", "mongodb://localhost:27017/college_admission")
client = MongoClient(MONGO_URL)
db = client["college_admission"]

# Clear existing data
db.colleges.delete_many({})

# Comprehensive college data with historical cutoffs
colleges_data = [
    # IITs
    {
        "name": "IIT Bombay",
        "location": "Mumbai",
        "state": "Maharashtra",
        "type": "IIT",
        "nirf_rank": 1,
        "branches": ["Computer Science", "Electrical", "Mechanical", "Civil", "Chemical", "Aerospace"],
        "fees_per_year": 2.5,
        "hostel_fees": 0.5,
        "total_fees": 10.0,
        "placement_avg": 21.5,
        "placement_highest": 1.8,
        "facilities_rating": 9.8,
        "campus_size": "550 acres",
        "notable_alumni": ["Sundar Pichai", "Parag Agrawal", "Nandan Nilekani"],
        "historical_cutoffs": [
            {"year": 2024, "branch": "Computer Science", "category": "General", "opening_rank": 1, "closing_rank": 66},
            {"year": 2024, "branch": "Computer Science", "category": "OBC", "opening_rank": 20, "closing_rank": 25},
            {"year": 2024, "branch": "Computer Science", "category": "SC", "opening_rank": 3, "closing_rank": 5},
            {"year": 2024, "branch": "Computer Science", "category": "ST", "opening_rank": 1, "closing_rank": 2},
            {"year": 2023, "branch": "Computer Science", "category": "General", "opening_rank": 1, "closing_rank": 63},
            {"year": 2023, "branch": "Computer Science", "category": "OBC", "opening_rank": 18, "closing_rank": 23},
            {"year": 2022, "branch": "Computer Science", "category": "General", "opening_rank": 1, "closing_rank": 60},
            {"year": 2024, "branch": "Electrical", "category": "General", "opening_rank": 150, "closing_rank": 450},
            {"year": 2024, "branch": "Electrical", "category": "OBC", "opening_rank": 80, "closing_rank": 180},
            {"year": 2024, "branch": "Mechanical", "category": "General", "opening_rank": 600, "closing_rank": 950},
        ]
    },
    {
        "name": "IIT Delhi",
        "location": "Delhi",
        "state": "Delhi",
        "type": "IIT",
        "nirf_rank": 2,
        "branches": ["Computer Science", "Electrical", "Mechanical", "Civil", "Chemical", "Mathematics & Computing"],
        "fees_per_year": 2.5,
        "hostel_fees": 0.4,
        "total_fees": 9.6,
        "placement_avg": 20.8,
        "placement_highest": 1.5,
        "facilities_rating": 9.7,
        "campus_size": "525 acres",
        "notable_alumni": ["Vinod Khosla", "Sachin Bansal", "Arvind Kejriwal"],
        "historical_cutoffs": [
            {"year": 2024, "branch": "Computer Science", "category": "General", "opening_rank": 67, "closing_rank": 115},
            {"year": 2024, "branch": "Computer Science", "category": "OBC", "opening_rank": 26, "closing_rank": 42},
            {"year": 2024, "branch": "Computer Science", "category": "SC", "opening_rank": 6, "closing_rank": 10},
            {"year": 2024, "branch": "Computer Science", "category": "ST", "opening_rank": 3, "closing_rank": 5},
            {"year": 2023, "branch": "Computer Science", "category": "General", "opening_rank": 64, "closing_rank": 108},
            {"year": 2022, "branch": "Computer Science", "category": "General", "opening_rank": 61, "closing_rank": 105},
            {"year": 2024, "branch": "Mathematics & Computing", "category": "General", "opening_rank": 116, "closing_rank": 180},
            {"year": 2024, "branch": "Electrical", "category": "General", "opening_rank": 200, "closing_rank": 550},
        ]
    },
    {
        "name": "IIT Madras",
        "location": "Chennai",
        "state": "Tamil Nadu",
        "type": "IIT",
        "nirf_rank": 1,
        "branches": ["Computer Science", "Electrical", "Mechanical", "Civil", "Chemical", "Aerospace"],
        "fees_per_year": 2.5,
        "hostel_fees": 0.35,
        "total_fees": 9.4,
        "placement_avg": 19.5,
        "placement_highest": 1.2,
        "facilities_rating": 9.8,
        "campus_size": "617 acres",
        "notable_alumni": ["Raghuram Rajan", "Jayant Narlikar", "Kris Gopalakrishnan"],
        "historical_cutoffs": [
            {"year": 2024, "branch": "Computer Science", "category": "General", "opening_rank": 116, "closing_rank": 184},
            {"year": 2024, "branch": "Computer Science", "category": "OBC", "opening_rank": 43, "closing_rank": 70},
            {"year": 2024, "branch": "Computer Science", "category": "SC", "opening_rank": 11, "closing_rank": 18},
            {"year": 2023, "branch": "Computer Science", "category": "General", "opening_rank": 109, "closing_rank": 176},
            {"year": 2022, "branch": "Computer Science", "category": "General", "opening_rank": 106, "closing_rank": 170},
            {"year": 2024, "branch": "Electrical", "category": "General", "opening_rank": 300, "closing_rank": 680},
        ]
    },
    {
        "name": "IIT Kanpur",
        "location": "Kanpur",
        "state": "Uttar Pradesh",
        "type": "IIT",
        "nirf_rank": 4,
        "branches": ["Computer Science", "Electrical", "Mechanical", "Civil", "Chemical", "Aerospace"],
        "fees_per_year": 2.5,
        "hostel_fees": 0.4,
        "total_fees": 9.6,
        "placement_avg": 18.9,
        "placement_highest": 1.0,
        "facilities_rating": 9.5,
        "campus_size": "1055 acres",
        "notable_alumni": ["Narayana Murthy", "Abhay Bhutada", "Roman Saini"],
        "historical_cutoffs": [
            {"year": 2024, "branch": "Computer Science", "category": "General", "opening_rank": 185, "closing_rank": 280},
            {"year": 2024, "branch": "Computer Science", "category": "OBC", "opening_rank": 71, "closing_rank": 110},
            {"year": 2024, "branch": "Computer Science", "category": "SC", "opening_rank": 19, "closing_rank": 30},
            {"year": 2023, "branch": "Computer Science", "category": "General", "opening_rank": 177, "closing_rank": 265},
            {"year": 2024, "branch": "Electrical", "category": "General", "opening_rank": 400, "closing_rank": 850},
        ]
    },
    {
        "name": "IIT Kharagpur",
        "location": "Kharagpur",
        "state": "West Bengal",
        "type": "IIT",
        "nirf_rank": 5,
        "branches": ["Computer Science", "Electrical", "Mechanical", "Civil", "Chemical", "Mining", "Aerospace"],
        "fees_per_year": 2.5,
        "hostel_fees": 0.3,
        "total_fees": 9.2,
        "placement_avg": 17.8,
        "placement_highest": 0.95,
        "facilities_rating": 9.4,
        "campus_size": "2100 acres",
        "notable_alumni": ["Vinod Gupta", "Jitendra Singh", "Aparajita Datta"],
        "historical_cutoffs": [
            {"year": 2024, "branch": "Computer Science", "category": "General", "opening_rank": 281, "closing_rank": 420},
            {"year": 2024, "branch": "Computer Science", "category": "OBC", "opening_rank": 111, "closing_rank": 165},
            {"year": 2024, "branch": "Computer Science", "category": "SC", "opening_rank": 31, "closing_rank": 48},
            {"year": 2023, "branch": "Computer Science", "category": "General", "opening_rank": 266, "closing_rank": 398},
            {"year": 2024, "branch": "Electrical", "category": "General", "opening_rank": 500, "closing_rank": 1100},
        ]
    },
    {
        "name": "IIT Roorkee",
        "location": "Roorkee",
        "state": "Uttarakhand",
        "type": "IIT",
        "nirf_rank": 6,
        "branches": ["Computer Science", "Electrical", "Mechanical", "Civil", "Chemical", "Architecture"],
        "fees_per_year": 2.5,
        "hostel_fees": 0.35,
        "total_fees": 9.4,
        "placement_avg": 16.5,
        "placement_highest": 0.85,
        "facilities_rating": 9.3,
        "campus_size": "365 acres",
        "notable_alumni": ["Binny Bansal", "Ajit Doval", "Sabeer Bhatia"],
        "historical_cutoffs": [
            {"year": 2024, "branch": "Computer Science", "category": "General", "opening_rank": 421, "closing_rank": 600},
            {"year": 2024, "branch": "Computer Science", "category": "OBC", "opening_rank": 166, "closing_rank": 235},
            {"year": 2024, "branch": "Computer Science", "category": "SC", "opening_rank": 49, "closing_rank": 72},
            {"year": 2023, "branch": "Computer Science", "category": "General", "opening_rank": 399, "closing_rank": 570},
            {"year": 2024, "branch": "Electrical", "category": "General", "opening_rank": 700, "closing_rank": 1350},
        ]
    },
    # NITs
    {
        "name": "NIT Trichy",
        "location": "Tiruchirappalli",
        "state": "Tamil Nadu",
        "type": "NIT",
        "nirf_rank": 9,
        "branches": ["Computer Science", "Electronics", "Electrical", "Mechanical", "Civil", "Chemical", "Instrumentation"],
        "fees_per_year": 1.5,
        "hostel_fees": 0.3,
        "total_fees": 6.0,
        "placement_avg": 12.5,
        "placement_highest": 0.45,
        "facilities_rating": 8.9,
        "campus_size": "800 acres",
        "notable_alumni": ["Karthik Subbaraj", "Sundar Raman", "Kiran Karnik"],
        "historical_cutoffs": [
            {"year": 2024, "branch": "Computer Science", "category": "General", "opening_rank": 1850, "closing_rank": 4820},
            {"year": 2024, "branch": "Computer Science", "category": "OBC", "opening_rank": 1200, "closing_rank": 2950},
            {"year": 2024, "branch": "Computer Science", "category": "SC", "opening_rank": 380, "closing_rank": 850},
            {"year": 2024, "branch": "Computer Science", "category": "ST", "opening_rank": 150, "closing_rank": 320},
            {"year": 2023, "branch": "Computer Science", "category": "General", "opening_rank": 1780, "closing_rank": 4650},
            {"year": 2022, "branch": "Computer Science", "category": "General", "opening_rank": 1720, "closing_rank": 4500},
            {"year": 2024, "branch": "Electronics", "category": "General", "opening_rank": 5000, "closing_rank": 9200},
            {"year": 2024, "branch": "Electrical", "category": "General", "opening_rank": 9500, "closing_rank": 14800},
        ]
    },
    {
        "name": "NIT Warangal",
        "location": "Warangal",
        "state": "Telangana",
        "type": "NIT",
        "nirf_rank": 10,
        "branches": ["Computer Science", "Electronics", "Electrical", "Mechanical", "Civil", "Chemical", "Biotechnology"],
        "fees_per_year": 1.5,
        "hostel_fees": 0.25,
        "total_fees": 5.8,
        "placement_avg": 11.8,
        "placement_highest": 0.42,
        "facilities_rating": 8.8,
        "campus_size": "256 acres",
        "notable_alumni": ["Satya Nadella (attended)", "Ajay Bhatt", "Jayaprakash Narayan"],
        "historical_cutoffs": [
            {"year": 2024, "branch": "Computer Science", "category": "General", "opening_rank": 2100, "closing_rank": 5200},
            {"year": 2024, "branch": "Computer Science", "category": "OBC", "opening_rank": 1350, "closing_rank": 3180},
            {"year": 2024, "branch": "Computer Science", "category": "SC", "opening_rank": 420, "closing_rank": 920},
            {"year": 2023, "branch": "Computer Science", "category": "General", "opening_rank": 2020, "closing_rank": 5020},
            {"year": 2022, "branch": "Computer Science", "category": "General", "opening_rank": 1950, "closing_rank": 4850},
            {"year": 2024, "branch": "Electronics", "category": "General", "opening_rank": 5500, "closing_rank": 9800},
        ]
    },
    {
        "name": "NIT Surathkal",
        "location": "Mangalore",
        "state": "Karnataka",
        "type": "NIT",
        "nirf_rank": 11,
        "branches": ["Computer Science", "Electronics", "Electrical", "Mechanical", "Civil", "Chemical", "Information Technology"],
        "fees_per_year": 1.5,
        "hostel_fees": 0.28,
        "total_fees": 5.92,
        "placement_avg": 11.2,
        "placement_highest": 0.38,
        "facilities_rating": 8.7,
        "campus_size": "295 acres",
        "notable_alumni": ["Rajeev Suri", "Satish Dhawan", "Shikha Sharma"],
        "historical_cutoffs": [
            {"year": 2024, "branch": "Computer Science", "category": "General", "opening_rank": 2500, "closing_rank": 6200},
            {"year": 2024, "branch": "Computer Science", "category": "OBC", "opening_rank": 1580, "closing_rank": 3750},
            {"year": 2024, "branch": "Computer Science", "category": "SC", "opening_rank": 480, "closing_rank": 1050},
            {"year": 2023, "branch": "Computer Science", "category": "General", "opening_rank": 2400, "closing_rank": 5980},
            {"year": 2024, "branch": "Information Technology", "category": "General", "opening_rank": 6500, "closing_rank": 10200},
        ]
    },
    {
        "name": "NIT Rourkela",
        "location": "Rourkela",
        "state": "Odisha",
        "type": "NIT",
        "nirf_rank": 16,
        "branches": ["Computer Science", "Electronics", "Electrical", "Mechanical", "Civil", "Chemical", "Metallurgy"],
        "fees_per_year": 1.4,
        "hostel_fees": 0.25,
        "total_fees": 5.5,
        "placement_avg": 10.5,
        "placement_highest": 0.35,
        "facilities_rating": 8.5,
        "campus_size": "648 acres",
        "notable_alumni": ["Dilip Shanghvi", "Arun Maira", "Tapan Misra"],
        "historical_cutoffs": [
            {"year": 2024, "branch": "Computer Science", "category": "General", "opening_rank": 5500, "closing_rank": 11200},
            {"year": 2024, "branch": "Computer Science", "category": "OBC", "opening_rank": 3200, "closing_rank": 6800},
            {"year": 2024, "branch": "Computer Science", "category": "SC", "opening_rank": 950, "closing_rank": 1850},
            {"year": 2023, "branch": "Computer Science", "category": "General", "opening_rank": 5320, "closing_rank": 10850},
            {"year": 2024, "branch": "Electronics", "category": "General", "opening_rank": 11500, "closing_rank": 17200},
        ]
    },
    {
        "name": "NIT Calicut",
        "location": "Kozhikode",
        "state": "Kerala",
        "type": "NIT",
        "nirf_rank": 13,
        "branches": ["Computer Science", "Electronics", "Electrical", "Mechanical", "Civil", "Chemical", "Architecture"],
        "fees_per_year": 1.45,
        "hostel_fees": 0.3,
        "total_fees": 5.8,
        "placement_avg": 10.8,
        "placement_highest": 0.38,
        "facilities_rating": 8.6,
        "campus_size": "625 acres",
        "notable_alumni": ["K. Radhakrishnan", "Adoor Gopalakrishnan", "Jassim Mohammed"],
        "historical_cutoffs": [
            {"year": 2024, "branch": "Computer Science", "category": "General", "opening_rank": 4200, "closing_rank": 9500},
            {"year": 2024, "branch": "Computer Science", "category": "OBC", "opening_rank": 2500, "closing_rank": 5800},
            {"year": 2024, "branch": "Computer Science", "category": "SC", "opening_rank": 750, "closing_rank": 1620},
            {"year": 2023, "branch": "Computer Science", "category": "General", "opening_rank": 4050, "closing_rank": 9180},
            {"year": 2024, "branch": "Electronics", "category": "General", "opening_rank": 9800, "closing_rank": 15500},
        ]
    },
    # IIITs
    {
        "name": "IIIT Hyderabad",
        "location": "Hyderabad",
        "state": "Telangana",
        "type": "IIIT",
        "nirf_rank": 7,
        "branches": ["Computer Science", "Electronics", "Computational Engineering"],
        "fees_per_year": 3.5,
        "hostel_fees": 0.4,
        "total_fees": 14.0,
        "placement_avg": 16.5,
        "placement_highest": 0.75,
        "facilities_rating": 9.2,
        "campus_size": "62 acres",
        "notable_alumni": ["Pavan Sondur", "Gaurav Mittal", "Srikanth Iyengar"],
        "historical_cutoffs": [
            {"year": 2024, "branch": "Computer Science", "category": "General", "opening_rank": 180, "closing_rank": 750},
            {"year": 2024, "branch": "Computer Science", "category": "OBC", "opening_rank": 90, "closing_rank": 380},
            {"year": 2024, "branch": "Computer Science", "category": "SC", "opening_rank": 28, "closing_rank": 110},
            {"year": 2023, "branch": "Computer Science", "category": "General", "opening_rank": 165, "closing_rank": 710},
            {"year": 2024, "branch": "Electronics", "category": "General", "opening_rank": 800, "closing_rank": 1850},
        ]
    },
    {
        "name": "IIIT Bangalore",
        "location": "Bangalore",
        "state": "Karnataka",
        "type": "IIIT",
        "nirf_rank": 15,
        "branches": ["Computer Science", "Electronics"],
        "fees_per_year": 3.8,
        "hostel_fees": 0.45,
        "total_fees": 15.2,
        "placement_avg": 15.2,
        "placement_highest": 0.62,
        "facilities_rating": 8.9,
        "campus_size": "25 acres",
        "notable_alumni": ["Flipkart founders team", "Amazon leaders", "Microsoft engineers"],
        "historical_cutoffs": [
            {"year": 2024, "branch": "Computer Science", "category": "General", "opening_rank": 850, "closing_rank": 2100},
            {"year": 2024, "branch": "Computer Science", "category": "OBC", "opening_rank": 480, "closing_rank": 1280},
            {"year": 2024, "branch": "Computer Science", "category": "SC", "opening_rank": 145, "closing_rank": 350},
            {"year": 2023, "branch": "Computer Science", "category": "General", "opening_rank": 800, "closing_rank": 2020},
        ]
    },
    {
        "name": "IIIT Delhi",
        "location": "Delhi",
        "state": "Delhi",
        "type": "IIIT",
        "nirf_rank": 17,
        "branches": ["Computer Science", "Electronics", "Computer Science & Design"],
        "fees_per_year": 3.2,
        "hostel_fees": 0.4,
        "total_fees": 12.8,
        "placement_avg": 14.8,
        "placement_highest": 0.58,
        "facilities_rating": 8.8,
        "campus_size": "25 acres",
        "notable_alumni": ["Startup founders", "Product leaders at FAANG"],
        "historical_cutoffs": [
            {"year": 2024, "branch": "Computer Science", "category": "General", "opening_rank": 950, "closing_rank": 2350},
            {"year": 2024, "branch": "Computer Science", "category": "OBC", "opening_rank": 520, "closing_rank": 1420},
            {"year": 2024, "branch": "Computer Science", "category": "SC", "opening_rank": 160, "closing_rank": 390},
            {"year": 2023, "branch": "Computer Science", "category": "General", "opening_rank": 900, "closing_rank": 2250},
        ]
    },
    {
        "name": "IIIT Allahabad",
        "location": "Prayagraj",
        "state": "Uttar Pradesh",
        "type": "IIIT",
        "nirf_rank": 20,
        "branches": ["Computer Science", "Information Technology", "Electronics"],
        "fees_per_year": 2.8,
        "hostel_fees": 0.35,
        "total_fees": 11.2,
        "placement_avg": 12.5,
        "placement_highest": 0.42,
        "facilities_rating": 8.5,
        "campus_size": "100 acres",
        "notable_alumni": ["Tech entrepreneurs", "Software architects"],
        "historical_cutoffs": [
            {"year": 2024, "branch": "Computer Science", "category": "General", "opening_rank": 2800, "closing_rank": 6500},
            {"year": 2024, "branch": "Computer Science", "category": "OBC", "opening_rank": 1650, "closing_rank": 3950},
            {"year": 2024, "branch": "Information Technology", "category": "General", "opening_rank": 6800, "closing_rank": 12200},
            {"year": 2023, "branch": "Computer Science", "category": "General", "opening_rank": 2700, "closing_rank": 6300},
        ]
    },
    # More NITs
    {
        "name": "NIT Karnataka (NITK)",
        "location": "Mangalore",
        "state": "Karnataka",
        "type": "NIT",
        "nirf_rank": 11,
        "branches": ["Computer Science", "Electronics", "Electrical", "Mechanical", "Civil", "Chemical", "Information Technology"],
        "fees_per_year": 1.5,
        "hostel_fees": 0.28,
        "total_fees": 5.92,
        "placement_avg": 11.5,
        "placement_highest": 0.40,
        "facilities_rating": 8.7,
        "campus_size": "300 acres",
        "notable_alumni": ["Industry leaders", "Entrepreneurs"],
        "historical_cutoffs": [
            {"year": 2024, "branch": "Computer Science", "category": "General", "opening_rank": 2400, "closing_rank": 6000},
            {"year": 2024, "branch": "Computer Science", "category": "OBC", "opening_rank": 1500, "closing_rank": 3650},
            {"year": 2024, "branch": "Information Technology", "category": "General", "opening_rank": 6200, "closing_rank": 11500},
        ]
    },
    {
        "name": "NIT Jaipur",
        "location": "Jaipur",
        "state": "Rajasthan",
        "type": "NIT",
        "nirf_rank": 18,
        "branches": ["Computer Science", "Electronics", "Electrical", "Mechanical", "Civil", "Chemical"],
        "fees_per_year": 1.4,
        "hostel_fees": 0.26,
        "total_fees": 5.64,
        "placement_avg": 10.2,
        "placement_highest": 0.35,
        "facilities_rating": 8.4,
        "campus_size": "325 acres",
        "notable_alumni": ["Corporate executives", "Civil servants"],
        "historical_cutoffs": [
            {"year": 2024, "branch": "Computer Science", "category": "General", "opening_rank": 6800, "closing_rank": 13500},
            {"year": 2024, "branch": "Computer Science", "category": "OBC", "opening_rank": 4200, "closing_rank": 8200},
            {"year": 2024, "branch": "Electronics", "category": "General", "opening_rank": 14000, "closing_rank": 21000},
        ]
    },
    {
        "name": "NIT Nagpur",
        "location": "Nagpur",
        "state": "Maharashtra",
        "type": "NIT",
        "nirf_rank": 22,
        "branches": ["Computer Science", "Electronics", "Electrical", "Mechanical", "Civil", "Metallurgy"],
        "fees_per_year": 1.4,
        "hostel_fees": 0.25,
        "total_fees": 5.5,
        "placement_avg": 9.8,
        "placement_highest": 0.32,
        "facilities_rating": 8.3,
        "campus_size": "220 acres",
        "notable_alumni": ["Industry professionals", "Researchers"],
        "historical_cutoffs": [
            {"year": 2024, "branch": "Computer Science", "category": "General", "opening_rank": 8200, "closing_rank": 16500},
            {"year": 2024, "branch": "Computer Science", "category": "OBC", "opening_rank": 5100, "closing_rank": 10200},
            {"year": 2024, "branch": "Electronics", "category": "General", "opening_rank": 17000, "closing_rank": 25000},
        ]
    },
    {
        "name": "NIT Kurukshetra",
        "location": "Kurukshetra",
        "state": "Haryana",
        "type": "NIT",
        "nirf_rank": 24,
        "branches": ["Computer Science", "Electronics", "Electrical", "Mechanical", "Civil", "Information Technology"],
        "fees_per_year": 1.4,
        "hostel_fees": 0.24,
        "total_fees": 5.44,
        "placement_avg": 9.5,
        "placement_highest": 0.30,
        "facilities_rating": 8.2,
        "campus_size": "300 acres",
        "notable_alumni": ["Tech professionals", "Government officials"],
        "historical_cutoffs": [
            {"year": 2024, "branch": "Computer Science", "category": "General", "opening_rank": 9500, "closing_rank": 18200},
            {"year": 2024, "branch": "Computer Science", "category": "OBC", "opening_rank": 5900, "closing_rank": 11500},
            {"year": 2024, "branch": "Information Technology", "category": "General", "opening_rank": 18500, "closing_rank": 28000},
        ]
    },
    {
        "name": "NIT Silchar",
        "location": "Silchar",
        "state": "Assam",
        "type": "NIT",
        "nirf_rank": 28,
        "branches": ["Computer Science", "Electronics", "Electrical", "Mechanical", "Civil"],
        "fees_per_year": 1.3,
        "hostel_fees": 0.22,
        "total_fees": 5.08,
        "placement_avg": 8.5,
        "placement_highest": 0.25,
        "facilities_rating": 7.9,
        "campus_size": "625 acres",
        "notable_alumni": ["Regional leaders", "Engineers"],
        "historical_cutoffs": [
            {"year": 2024, "branch": "Computer Science", "category": "General", "opening_rank": 15000, "closing_rank": 28000},
            {"year": 2024, "branch": "Computer Science", "category": "OBC", "opening_rank": 9500, "closing_rank": 17500},
            {"year": 2024, "branch": "Electronics", "category": "General", "opening_rank": 29000, "closing_rank": 42000},
        ]
    },
    {
        "name": "NIT Durgapur",
        "location": "Durgapur",
        "state": "West Bengal",
        "type": "NIT",
        "nirf_rank": 25,
        "branches": ["Computer Science", "Electronics", "Electrical", "Mechanical", "Civil", "Metallurgy"],
        "fees_per_year": 1.35,
        "hostel_fees": 0.23,
        "total_fees": 5.32,
        "placement_avg": 9.2,
        "placement_highest": 0.28,
        "facilities_rating": 8.1,
        "campus_size": "187 acres",
        "notable_alumni": ["Professionals in PSUs", "Private sector leaders"],
        "historical_cutoffs": [
            {"year": 2024, "branch": "Computer Science", "category": "General", "opening_rank": 11200, "closing_rank": 22000},
            {"year": 2024, "branch": "Computer Science", "category": "OBC", "opening_rank": 7000, "closing_rank": 13800},
            {"year": 2024, "branch": "Electronics", "category": "General", "opening_rank": 22500, "closing_rank": 35000},
        ]
    },
    {
        "name": "NIT Bhopal",
        "location": "Bhopal",
        "state": "Madhya Pradesh",
        "type": "NIT",
        "nirf_rank": 30,
        "branches": ["Computer Science", "Electronics", "Electrical", "Mechanical", "Civil"],
        "fees_per_year": 1.3,
        "hostel_fees": 0.22,
        "total_fees": 5.08,
        "placement_avg": 8.8,
        "placement_highest": 0.26,
        "facilities_rating": 8.0,
        "campus_size": "650 acres",
        "notable_alumni": ["Engineers", "Researchers"],
        "historical_cutoffs": [
            {"year": 2024, "branch": "Computer Science", "category": "General", "opening_rank": 13500, "closing_rank": 25500},
            {"year": 2024, "branch": "Computer Science", "category": "OBC", "opening_rank": 8500, "closing_rank": 16000},
        ]
    },
    {
        "name": "NIT Jamshedpur",
        "location": "Jamshedpur",
        "state": "Jharkhand",
        "type": "NIT",
        "nirf_rank": 32,
        "branches": ["Computer Science", "Electronics", "Electrical", "Mechanical", "Civil", "Metallurgy"],
        "fees_per_year": 1.25,
        "hostel_fees": 0.20,
        "total_fees": 4.9,
        "placement_avg": 8.2,
        "placement_highest": 0.24,
        "facilities_rating": 7.8,
        "campus_size": "340 acres",
        "notable_alumni": ["Steel industry professionals", "Tech workers"],
        "historical_cutoffs": [
            {"year": 2024, "branch": "Computer Science", "category": "General", "opening_rank": 17500, "closing_rank": 32000},
            {"year": 2024, "branch": "Computer Science", "category": "OBC", "opening_rank": 11000, "closing_rank": 20000},
        ]
    },
    {
        "name": "NIT Patna",
        "location": "Patna",
        "state": "Bihar",
        "type": "NIT",
        "nirf_rank": 26,
        "branches": ["Computer Science", "Electronics", "Electrical", "Mechanical", "Civil"],
        "fees_per_year": 1.28,
        "hostel_fees": 0.21,
        "total_fees": 4.96,
        "placement_avg": 8.6,
        "placement_highest": 0.25,
        "facilities_rating": 7.9,
        "campus_size": "28 acres",
        "notable_alumni": ["Government officials", "Entrepreneurs"],
        "historical_cutoffs": [
            {"year": 2024, "branch": "Computer Science", "category": "General", "opening_rank": 14200, "closing_rank": 27000},
            {"year": 2024, "branch": "Computer Science", "category": "OBC", "opening_rank": 8900, "closing_rank": 16800},
        ]
    },
    {
        "name": "NIT Allahabad",
        "location": "Prayagraj",
        "state": "Uttar Pradesh",
        "type": "NIT",
        "nirf_rank": 21,
        "branches": ["Computer Science", "Electronics", "Electrical", "Mechanical", "Civil", "Information Technology"],
        "fees_per_year": 1.38,
        "hostel_fees": 0.24,
        "total_fees": 5.48,
        "placement_avg": 9.5,
        "placement_highest": 0.31,
        "facilities_rating": 8.2,
        "campus_size": "220 acres",
        "notable_alumni": ["IAS officers", "Tech leaders"],
        "historical_cutoffs": [
            {"year": 2024, "branch": "Computer Science", "category": "General", "opening_rank": 10200, "closing_rank": 19500},
            {"year": 2024, "branch": "Computer Science", "category": "OBC", "opening_rank": 6400, "closing_rank": 12200},
        ]
    }
]

# Insert all college data
result = db.colleges.insert_many(colleges_data)
print(f"✅ Successfully seeded {len(result.inserted_ids)} colleges into the database!")

# Create indexes for faster queries
db.colleges.create_index([("name", 1)])
db.colleges.create_index([("location", 1)])
db.colleges.create_index([("branches", 1)])
db.colleges.create_index([("total_fees", 1)])

print("✅ Created indexes for optimized queries!")
print("\n📊 Database seeding complete!")
print(f"Total colleges: {db.colleges.count_documents({})}")
